import { saveAs } from "file-saver";
import type { RunRecord } from "@/lib/db/dexie";

export function exportRunToMarkdown(run: RunRecord): string {
  const brand = (run.brand_snapshot as Record<string, Record<string, string>>)?.identity?.name || "Unknown";
  const lines = [
    `# ${run.parsed_fields.title || "Untitled Pin"}`,
    "",
    `**Brand:** ${brand}`,
    `**Niche:** ${run.niche}`,
    `**Date:** ${run.target_date}`,
    `**Status:** ${run.status}`,
    `**QC Score:** ${run.qc_results.score}/10`,
    "",
    "## Description",
    "",
    String(run.parsed_fields.description || ""),
    "",
    "## Hashtags",
    "",
    (run.parsed_fields.hashtags as string[])?.join(" ") || "",
    "",
    "## Image Prompt A (Illustrated)",
    "",
    String(run.parsed_fields.prompt_a || ""),
    "",
    "## Image Prompt B (Photorealistic)",
    "",
    String(run.parsed_fields.prompt_b || ""),
    "",
    "---",
    "",
    `*Generated by PinHub — Atelier Workspace on ${run.created_at}*`,
    `*Provider: ${run.provider} | Model: ${run.model} | Cost: $${run.cost_estimate.toFixed(4)}*`,
  ];

  return lines.join("\n");
}

export function exportRunsToMarkdown(runs: RunRecord[], filename?: string): void {
  const md = runs.map(exportRunToMarkdown).join("\n\n---\n\n");
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  saveAs(blob, filename || `pinhub-export-${new Date().toISOString().split("T")[0]}.md`);
}
