"use client";

import React from "react";
import { Document, Page, StyleSheet, Text, View, pdf } from "@react-pdf/renderer";
import { saveAs } from "file-saver";

interface ExportArgs {
  title: string;
  subtitle?: string;
  body: string;
  filename: string;
}

const styles = StyleSheet.create({
  page: {
    padding: 48,
    fontSize: 11,
    lineHeight: 1.55,
    color: "#3F2A1D",
    backgroundColor: "#FAF6EE",
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#C9A99A",
  },
  title: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
    color: "#3E2723",
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 10,
    color: "#7A6B5D",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  h1: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: "#3E2723",
    marginTop: 18,
    marginBottom: 8,
  },
  h2: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    color: "#3E2723",
    marginTop: 14,
    marginBottom: 6,
  },
  h3: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: "#5C4435",
    marginTop: 10,
    marginBottom: 4,
  },
  paragraph: {
    marginBottom: 6,
  },
  bullet: {
    flexDirection: "row",
    marginBottom: 4,
    paddingLeft: 8,
  },
  bulletDot: {
    width: 10,
  },
  bulletText: {
    flex: 1,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 48,
    right: 48,
    fontSize: 8,
    color: "#7A6B5D",
    borderTopWidth: 1,
    borderTopColor: "#C9A99A33",
    paddingTop: 6,
    textAlign: "center",
  },
});

function renderMarkdown(md: string): React.ReactElement[] {
  const lines = md.split("\n");
  const nodes: React.ReactElement[] = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const h1 = /^#\s+(.*)$/.exec(line);
    const h2 = /^##\s+(.*)$/.exec(line);
    const h3 = /^###\s+(.*)$/.exec(line);
    if (h1) {
      nodes.push(
        React.createElement(Text, { key: `n-${i}`, style: styles.h1 }, h1[1])
      );
      i++;
      continue;
    }
    if (h2) {
      nodes.push(
        React.createElement(Text, { key: `n-${i}`, style: styles.h2 }, h2[1])
      );
      i++;
      continue;
    }
    if (h3) {
      nodes.push(
        React.createElement(Text, { key: `n-${i}`, style: styles.h3 }, h3[1])
      );
      i++;
      continue;
    }
    const bullet = /^\s*[-*]\s+(.*)$/.exec(line);
    if (bullet) {
      nodes.push(
        React.createElement(
          View,
          { key: `n-${i}`, style: styles.bullet },
          React.createElement(Text, { style: styles.bulletDot }, "•"),
          React.createElement(Text, { style: styles.bulletText }, bullet[1])
        )
      );
      i++;
      continue;
    }
    const numbered = /^\s*(\d+)\.\s+(.*)$/.exec(line);
    if (numbered) {
      nodes.push(
        React.createElement(
          View,
          { key: `n-${i}`, style: styles.bullet },
          React.createElement(
            Text,
            { style: styles.bulletDot },
            `${numbered[1]}.`
          ),
          React.createElement(Text, { style: styles.bulletText }, numbered[2])
        )
      );
      i++;
      continue;
    }
    if (line.trim().length === 0) {
      nodes.push(
        React.createElement(Text, { key: `n-${i}`, style: styles.paragraph }, " ")
      );
      i++;
      continue;
    }
    nodes.push(
      React.createElement(
        Text,
        { key: `n-${i}`, style: styles.paragraph },
        line
      )
    );
    i++;
  }
  return nodes;
}

function GuideDocument({
  title,
  subtitle,
  body,
}: {
  title: string;
  subtitle?: string;
  body: string;
}) {
  const generatedAt = new Date().toLocaleString();
  return React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: "A4", style: styles.page, wrap: true },
      React.createElement(
        View,
        { style: styles.header },
        React.createElement(Text, { style: styles.title }, title),
        subtitle
          ? React.createElement(Text, { style: styles.subtitle }, subtitle)
          : null
      ),
      ...renderMarkdown(body),
      React.createElement(
        Text,
        { style: styles.footer, fixed: true },
        `Generated by PinHub · ${generatedAt}`
      )
    )
  );
}

export async function exportGuideAsPDF({
  title,
  subtitle,
  body,
  filename,
}: ExportArgs): Promise<void> {
  const doc = GuideDocument({ title, subtitle, body });
  const blob = await pdf(doc).toBlob();
  saveAs(blob, filename);
}
